// Generates a curated barrel entry + componentSrcMap for the Eden DS sync.
// Usage: node gen-entry.mjs <repoRoot>
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'node:fs';
import { join, basename, relative } from 'node:path';

const repo = process.argv[2];
if (!repo) { console.error('need repoRoot'); process.exit(1); }
const srcComp = join(repo, 'src', 'components');

// --- denylist of ui files (collisions / context-heavy) ---
const UI_DENY = new Set(['sonner.tsx']); // Toaster collides with toaster.tsx

// --- curated Eden presentational components (vetted: no supabase module-eval import) ---
const EDEN = [
  'quiz/AxisSpectrum.tsx',
  'landing/BotanicalAccents.tsx',
  'landing/WorldviewBand.tsx',
  'apothecary/PublicTierCard.tsx',
  'apothecary/TierComparison.tsx',
  'apothecary/PageSkeleton.tsx',
  'apothecary/HerbCard.tsx',
  'MateriaMedicaPlate.tsx',
];

// Per-file principal-name override: list ONLY these names as components (cards).
// BotanicalAccents exports 4 SVGs, but the founder dislikes the leaf line-art —
// keep only GoldDivider as a card (the file still bundles for completeness).
const PRINCIPAL_OVERRIDE = {
  'landing/BotanicalAccents.tsx': ['GoldDivider'],
};

// collect ui files
const uiDir = join(srcComp, 'ui');
const uiFiles = readdirSync(uiDir)
  .filter((f) => f.endsWith('.tsx') && !UI_DENY.has(f))
  .map((f) => `ui/${f}`);

const files = [...uiFiles, ...EDEN].filter((rel) => existsSync(join(srcComp, rel)));

// extract exported PascalCase names (both `export const/function/class X` and `export { X, Y }`)
function exportsOf(text) {
  const names = new Set();
  const re1 = /export\s+(?:default\s+)?(?:const|function|class)\s+([A-Z][A-Za-z0-9]*)/g;
  let m;
  while ((m = re1.exec(text))) names.add(m[1]);
  const re2 = /export\s*\{([^}]*)\}/g;
  while ((m = re2.exec(text))) {
    for (const part of m[1].split(',')) {
      const id = part.trim().split(/\s+as\s+/).pop().trim();
      if (/^[A-Z][A-Za-z0-9]*$/.test(id)) names.add(id);
    }
  }
  return names;
}

function pascal(file) {
  return basename(file, '.tsx').replace(/(^|[-_])([a-z0-9])/g, (_, __, c) => c.toUpperCase());
}

const barrelLines = [];
const srcMap = {};
const principalsByFile = {};

for (const rel of files) {
  const abs = join(srcComp, rel);
  const text = readFileSync(abs, 'utf8');
  const exps = exportsOf(text);
  const importPath = '@/components/' + rel.replace(/\.tsx$/, '');
  barrelLines.push(`export * from ${JSON.stringify(importPath)};`);

  const repoRelPath = 'src/components/' + rel;
  let principals;
  if (PRINCIPAL_OVERRIDE[rel]) {
    principals = PRINCIPAL_OVERRIDE[rel].filter((n) => exps.has(n));
  } else {
    const want = pascal(rel);
    principals = exps.has(want) ? [want] : (exps.size ? [[...exps][0]] : []);
  }
  principalsByFile[rel] = principals;
  for (const name of principals) srcMap[name] = repoRelPath;
}

// write barrel
const barrel = `// AUTO-GENERATED by design-sync gen-entry.mjs — curated Eden DS entry.\n${barrelLines.join('\n')}\n`;
writeFileSync(join(repo, 'eden-ds-entry.tsx'), barrel);

// emit componentSrcMap json
const dsDir = join(repo, '.design-sync');
if (!existsSync(dsDir)) mkdirSync(dsDir, { recursive: true });
writeFileSync(join(dsDir, '.componentSrcMap.json'), JSON.stringify(srcMap, null, 2));

console.log(`files: ${files.length}`);
console.log(`components: ${Object.keys(srcMap).length}`);
console.log('principals:');
for (const [rel, ps] of Object.entries(principalsByFile)) console.log(`  ${rel} -> ${ps.join(', ') || '(none!)'}`);
