// Auto-generated by design-sync. Maps herb slug -> public plate URL.
export const PLATE_SRC: Record<string, string> = {
  'calendula': "/materia-medica/calendula.webp",
  'catnip': "/materia-medica/catnip.webp",
  'chamomile': "/materia-medica/chamomile.webp",
  'elderberry': "/materia-medica/elderberry.webp",
  'fennel': "/materia-medica/fennel.webp",
  'ginger': "/materia-medica/ginger.webp",
  'lavender': "/materia-medica/lavender.webp",
  'lemon-balm': "/materia-medica/lemon-balm.webp",
  'linden': "/materia-medica/linden.webp",
  'marshmallow-root': "/materia-medica/marshmallow-root.webp",
  'mullein': "/materia-medica/mullein.webp",
  'nettle': "/materia-medica/nettle.webp",
  'peppermint': "/materia-medica/peppermint.webp",
  'plantain': "/materia-medica/plantain.webp",
  'slippery-elm': "/materia-medica/slippery-elm.webp",
  'tulsi': "/materia-medica/tulsi.webp",
};
