-- Practitioner buildout Phase 0 (TL-5): load the tier-visibility field map
-- into prod. schema_fields existed as an empty table while the 74-row map
-- lived only in the master spreadsheet
-- (Eden_Apothecary_Master_Herb_Database_v2.xlsx :: Schema_Fields tab —
-- 74 data rows; the spec's "75" counted the header). Card rendering and the
-- Practitioner clinical surfaces read tier gating from this table rather
-- than hard-coding it. Idempotent: ON CONFLICT DO NOTHING.

INSERT INTO public.schema_fields (field_id, sheet, column_name, tier, display_name, description)
VALUES
  ('F001', 'Herbs', 'Common Name', '1', 'Common Name', 'Primary English name'),
  ('F002', 'Herbs', 'Latin Name', '1', 'Botanical Name', 'Binomial nomenclature'),
  ('F003', 'Herbs', 'Part Used', '1', 'Part Used', 'Plant part(s) employed medicinally'),
  ('F004', 'Herbs', 'Chief Complaints', '1', 'Chief Complaints', 'Primary indications in traditional use'),
  ('F005', 'Herbs', 'Cautions', '1', 'Cautions', 'General clinical cautions and warnings'),
  ('F006', 'Herbs', 'Contraindications (General)', '1', 'Contraindications (General)', 'General contraindications'),
  ('F007', 'Herbs', 'Pregnancy Safety', '1', 'Pregnancy', 'Pregnancy safety status'),
  ('F008', 'Herbs', 'Breastfeeding Safety', '1', 'Lactation / Breastfeeding', 'Breastfeeding safety status (currently empty, for future population)'),
  ('F009', 'Herbs', 'Children Safety', '1', 'Pediatric / Children', 'Pediatric safety status'),
  ('F010', 'Herbs', 'Drug Interactions', '1', 'Drug Interactions', 'Known pharmaceutical interactions'),
  ('F011', 'Herbs', 'Biblical / Traditional Reference', '1', 'Biblical / Traditional Reference', 'Scriptural or classical historical citation'),
  ('F012', 'Herbs', 'Stewardship Note', '1', 'Stewardship Note', 'Ethical / theological framing of the herbs use'),
  ('F013', 'Herbs', 'Energetics Summary', '1', 'Energetics Summary', 'One-line plain-language terrain summary'),
  ('F014', 'Herbs', 'Refer Threshold', '1', 'Refer Threshold', 'Conditions requiring referral to a licensed practitioner'),
  ('F015', 'Herbs', 'Pronunciation', '1', 'Pronunciation', 'Phonetic rendering of the Latin name'),
  ('F016', 'Herbs', 'Image Filename', '1', 'Image', 'Botanical image filename'),
  ('F017', 'Herbs', 'Status', '1', 'Status', 'Draft / Reviewed / Published'),
  ('F018', 'Herbs', 'Family', '2', 'Plant Family', 'Botanical family'),
  ('F019', 'Herbs', 'Dosage Notes', '2', 'Dosage', 'Typical adult dosage guidance'),
  ('F020', 'Herbs', 'Preparation Methods', '2', 'Preparations', 'Traditional preparation forms'),
  ('F021', 'Herbs', 'Primary Source(s)', '2', 'Primary Sources', 'Primary public-domain citations (legacy field; being migrated to Citations table)'),
  ('F022', 'Herbs', 'Taste', '3', 'Taste', 'Traditional taste profile'),
  ('F023', 'Herbs', 'Temperature', '3', 'Temperature', 'Warming / cooling energetic'),
  ('F024', 'Herbs', 'Moisture', '3', 'Moisture', 'Moistening / drying energetic'),
  ('F025', 'Herbs', 'Created Date', '3', 'Created', 'Record creation date (internal)'),
  ('F026', 'Herbs_TissueStates_Indicated', 'State ID', '2', 'Indicated Tissue States', 'Tissue states this herb addresses'),
  ('F027', 'Herbs_TissueStates_Indicated', 'Strength of Indication', '3', 'Strength', 'Primary / Secondary / Supportive'),
  ('F028', 'Herbs_TissueStates_Indicated', 'Notes', '3', 'Clinical Note', 'Qualifier / nuance'),
  ('F029', 'Herbs_TissueStates_Contraindica', 'State ID', '2', 'Contraindicated Tissue States', 'Tissue states this herb would aggravate'),
  ('F030', 'Herbs_TissueStates_Contraindica', 'Strength of Indication', '3', 'Caution Strength', 'Degree of contraindication'),
  ('F031', 'Herbs_TissueStates_Contraindica', 'Notes', '3', 'Clinical Note', 'Qualifier / nuance'),
  ('F032', 'Herbs_Systems', 'System ID', '2', 'System Affinity', 'Body systems the herb influences'),
  ('F033', 'Herbs_Systems', 'Strength of Indication', '3', 'Affinity Strength', 'Primary / Secondary'),
  ('F034', 'Herbs_Systems', 'Notes', '3', 'Clinical Note', 'Qualifier'),
  ('F035', 'Herbs_Actions', 'Action ID', '2', 'Actions', 'Herbal actions'),
  ('F036', 'Herbs_Actions', 'Strength of Indication', '3', 'Action Strength', 'Primary / Secondary / Supportive'),
  ('F037', 'Herbs_Actions', 'Notes', '3', 'Clinical Note', 'Qualifier'),
  ('F038', 'Herbs_Constitutions', 'Constitution ID', '2', 'Western Constitution', 'Humoral / energetic constitutional indication'),
  ('F039', 'Herbs_Constitutions', 'Relationship', '2', 'Constitutional Relationship', 'Suits / Aggravates'),
  ('F040', 'Herbs_Constitutions', 'Strength of Indication', '3', 'Strength', 'Primary / Secondary'),
  ('F041', 'Herbs_Constitutions', 'Notes', '3', 'Clinical Note', 'Qualifier'),
  ('F042', 'Herbs_Preparations', 'Prep ID', '2', 'Preparation Forms', 'Traditional preparation forms'),
  ('F043', 'Herbs_Preparations', 'Strength of Indication', '3', 'Preferred Form', 'Preferred / Acceptable'),
  ('F044', 'Herbs_Preparations', 'Notes', '3', 'Preparation Note', 'Dosing or technique detail'),
  ('F045', 'Herbs_Complaints', 'Complaint ID', '1', 'Indications', 'Traditional indications'),
  ('F046', 'Herbs_Complaints', 'Strength of Indication', '2', 'Indication Strength', 'Specific / General / Supportive'),
  ('F047', 'Herbs_Complaints', 'Notes', '3', 'Clinical Note', 'Qualifier'),
  ('F048', 'Herbs_Tastes', 'Taste ID', '3', 'Taste Profile', 'Traditional taste classification'),
  ('F049', 'Herbs_Tastes', 'Strength of Indication', '3', 'Taste Prominence', 'Primary / Secondary'),
  ('F050', 'Herbs_Tastes', 'Notes', '3', 'Taste Note', 'Qualifier'),
  ('F051', 'Herbs_Doshas_Match', 'Dosha ID', '3', 'Ayurvedic Dosha (balances)', 'Doshas this herb pacifies'),
  ('F052', 'Herbs_Doshas_Match', 'Strength of Indication', '3', 'Strength', 'Primary / Secondary'),
  ('F053', 'Herbs_Doshas_Match', 'Notes', '3', 'Ayurvedic Note', 'Qualifier'),
  ('F054', 'Herbs_Doshas_Aggravates', 'Dosha ID', '3', 'Ayurvedic Dosha (aggravates)', 'Doshas this herb may aggravate'),
  ('F055', 'Herbs_Doshas_Aggravates', 'Strength of Indication', '3', 'Strength', 'Degree of aggravation'),
  ('F056', 'Herbs_Doshas_Aggravates', 'Notes', '3', 'Ayurvedic Note', 'Qualifier'),
  ('F057', 'Herbs_TCM_Indicated', 'Pattern ID', '3', 'TCM Pattern (indicated)', 'TCM patterns this herb addresses'),
  ('F058', 'Herbs_TCM_Indicated', 'Strength of Indication', '3', 'Strength', 'Primary / Secondary'),
  ('F059', 'Herbs_TCM_Indicated', 'Notes', '3', 'TCM Note', 'Qualifier'),
  ('F060', 'Herbs_TCM_Contraindicated', 'Pattern ID', '3', 'TCM Pattern (contraindicated)', 'TCM patterns this herb would aggravate'),
  ('F061', 'Herbs_TCM_Contraindicated', 'Strength of Indication', '3', 'Caution Strength', 'Degree of contraindication'),
  ('F062', 'Herbs_TCM_Contraindicated', 'Notes', '3', 'TCM Note', 'Qualifier'),
  ('F063', 'Contraindications', 'Type', '1', 'Contraindication Type', 'Condition / Drug / Population / Herb'),
  ('F064', 'Contraindications', 'Interacting Entity', '1', 'Interacting Entity', 'What the herb conflicts with'),
  ('F065', 'Contraindications', 'Severity', '1', 'Severity', 'Absolute / Major / Moderate / Minor'),
  ('F066', 'Contraindications', 'Mechanism / Rationale', '2', 'Mechanism', 'Pharmacological or terrain rationale'),
  ('F067', 'Contraindications', 'Clinical Guidance', '2', 'Guidance', 'Practitioner-level guidance'),
  ('F068', 'Contraindications', 'Source Citation', '3', 'Source', 'Citation reference'),
  ('F069', 'Citations_Herbs', 'Citation ID', '3', 'Citations', 'Public-domain source citations for this herb'),
  ('F070', 'Citations_Herbs', 'Field Cited', '3', 'Field Cited', 'Which herb field the citation supports'),
  ('F071', 'Herbs', 'Tier (Free/Paid)', '0', 'Access Tier (legacy)', 'Legacy access-control field; superseded by Schema_Fields Tier mapping in v2. Retain for audit.'),
  ('F072', 'Herbs', 'Last Updated', '0', 'Last Updated', 'Internal revision date'),
  ('F073', 'Herbs', 'Notes', '3', 'Scholarly Notes', 'Traditional/historical/scholarly notes about the herb'),
  ('F074', 'Herbs', 'Secondary Source(s)', '3', 'Secondary Sources', 'Secondary sources (legacy; being migrated to Citations table)')
ON CONFLICT (field_id) DO NOTHING;
